### ISSUE TITLE
Apply CFS tweak even with secure boot enabled

### ISSUE THREAD

**Issue by Froggy232** [KyleGospo/system76-scheduler#23]
Hi,
I understand that there is no way to dinamically tweak the CFS scheduler to TKG value when on AC.
As I use a dekstop computer that is always on AC, is there a way to apply theses changes elswhere, so I can enable secure boot again even if it means I don't use system76-scheduler for that and lost the dynamic switching feature?
Thanks you!

**Comment by KyleGospo** [comment]
Not fixable
