### ISSUE TITLE
Laptop overheating after running system76-scheduler

### ISSUE THREAD

**Issue by caike08** [KyleGospo/system76-scheduler#4]
Hello, 

First of all, thank you for bringing this project to Fedora. I managed to try it on my Lenovo Ideapad 5 14ARE05 and I could see some performance bump!

But, one thing I could notice was that the computer started to heat up a little while doing simple tasks, e.g. using the browser, a few tabs opened. Normally my laptop operates around 40-50 celsius while on idle, and 65-75 while running a more demand task (playing CS GO).

I would expect it to heat up while playing a game, but not while doing a simple task. 

I also noticed that it was overheating while running on battery too. 

So I just wanted to check if that is expected :)

**Comment by KyleGospo** [comment]
Hi there!

That definitely doesn't sound like the correct behavior to me, this is mostly just adjusting process priority. It's possible what you're seeing is a result of the scheduler adjustments that this makes to decrease latency, but those are reverted back to stock values if you're not connected to wall power (and only work in the first place if Secure Boot is disabled)

**Comment by caike08** [comment]
Got it! In fact, my laptop has Secure Boot enabled 😕

I also forgot to mention that the temperatures wouldn't go below 80 degrees Celsius after installing the scheduler, unless there was nothing else running, e.g. an open window. 

Closing all active windows will make temperatures go back to stock.

I also use `tlp` instead of `power-profiles-daemon`. And, I use `pop-shell`.

Isn't it possible to use this package if Secure Boot is enabled then? 

Is there anything that I can do to give you some log file of which is happening when the package is running, by the way?

**Comment by KyleGospo** [comment]
What's your CPU usage while this is happening?
Can you give me the output of `systemctl status com.system76.Scheduler.service`

It's possible to use this with Secure Boot, you just won't get the scheduler tweaks applied.
I opened an issue upstream for that: https://github.com/pop-os/system76-scheduler/issues/50

**Comment by caike08** [comment]
Without `com.system76.Scheduler.service` running, I just opened System Monitor from Fedora, I have two browsers opened: Vivaldi and Firefox, with a few tabs opened each all up to date:

![image](https://user-images.githubusercontent.com/4422230/172019675-7db6e5fa-6dc3-4a47-ab4d-ba1f8ba7eb38.png)

Temperatures were around 45-50 degrees Celsius.

Now with `com.system76.Scheduler.service` up and running, Temperatures were around 65 degrees at first, but now they are back to 40-50's. CPU usage is looking good too:

![image](https://user-images.githubusercontent.com/4422230/172020088-d8c2d4b7-709a-4802-8c71-05a4ffaee1ef.png)

I no longer had it installed, as the temperatures were higher than I wanted. Now that I installed it back, it seems it is working normally. One thing that I noticed before was that one of the cores would peak to 100% while the others would stay around 20%. And each core would peak for a moment. Perhaps that was why temperatures were high. But from what I could see, the problem is no longer present now :)

This is the output of `systemctl status com.system76.Scheduler.service`:

```
Created symlink /etc/systemd/system/multi-user.target.wants/com.system76.Scheduler.service → /usr/lib/systemd/system/com.system76.Scheduler.service.
❯ systemctl status com.system76.Scheduler.service
● com.system76.Scheduler.service - Automatically configure CPU scheduler for responsiveness on AC
     Loaded: loaded (/usr/lib/systemd/system/com.system76.Scheduler.service; enabled; vendor preset: disabled)
     Active: active (running) since Sat 2022-06-04 15:00:07 -03; 51s ago
   Main PID: 79387 (system76-schedu)
      Tasks: 5 (limit: 18379)
     Memory: 79.5M
        CPU: 1.295s
     CGroup: /system.slice/com.system76.Scheduler.service
             ├─ 79387 /usr/bin/system76-scheduler daemon
             └─ 79390 /usr/bin/python3 /usr/share/bcc/tools/execsnoop

Jun 04 15:00:07 fedora system76-scheduler[79387]:         (Assignment(CpuPriority(0), Standard), {"dbus", "sshd", "systemd"})
Jun 04 15:00:07 fedora system76-scheduler[79387]:         (Assignment(CpuPriority(9), Idle), {"ModemManager", "NetworkManager", "accounts-daemon", "acpid", "automount", "avahi-daemon", "bluetoothd", "colord", ">
Jun 04 15:00:07 fedora system76-scheduler[79387]:         (Assignment(CpuPriority(19), Idle), {"FAHClient", "FAHCoreWrapper", "apt", "apt-get", "boinc", "c++", "cargo", "clang", "cpp", "dpkg", "flatpak", "fossi>
Jun 04 15:00:07 fedora system76-scheduler[79387]:  INFO system76_scheduler::config: /etc/system76-scheduler/assignments/extra.ron:
Jun 04 15:00:07 fedora system76-scheduler[79387]:         (Assignment(CpuPriority(9), Idle), {"fx_cast_bridge", "protonmail-bridge", "rslsync"})
Jun 04 15:00:07 fedora system76-scheduler[79387]:         (Assignment(CpuPriority(19), Idle), {"dnf", "duperemove", "rpm", "yum", "zypper"})
Jun 04 15:00:07 fedora system76-scheduler[79387]: failed to set value in /sys/kernel/debug/sched/latency_ns: Operation not permitted (os error 1)
Jun 04 15:00:07 fedora system76-scheduler[79387]: failed to set value in /sys/kernel/debug/sched/min_granularity_ns: Operation not permitted (os error 1)
Jun 04 15:00:07 fedora system76-scheduler[79387]: failed to set value in /sys/kernel/debug/sched/wakeup_granularity_ns: Operation not permitted (os error 1)
Jun 04 15:00:07 fedora system76-scheduler[79387]: failed to set value in /sys/kernel/debug/sched/preempt: Operation not permitted (os error 1)


```

**Comment by KyleGospo** [comment]
You may have had an older version installed, there was an upstream bug that would cause 100% CPU usage on one core that was patched and merged in a few days ago. Glad it's working normally for you now!

https://github.com/pop-os/system76-scheduler/issues/47

Let me know if you see this again and just send me the same info so I can look into it. Above issue was due to execsnoop not loading properly.

**Comment by caike08** [comment]
I sure will! Thank you for bringing it to Fedora :)
